In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")
warnings.filterwarnings("ignore", 
                        category=UserWarning, message=".* ve3rsion 1.0.02 when using version 1.3.0.",
                        module='sklearn')
%matplotlib inline
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import scipy.stats as stats
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.linear_model import LogisticRegression
import statsmodels.api as sm
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from statsmodels.stats.outliers_influence import variance_inflation_factor
from collections import Counter
from collections import OrderedDict
from tabulate import tabulate
from sklearn.cluster import KMeans, AgglomerativeClustering, Birch, DBSCAN
from sklearn.metrics import silhouette_score, calinski_harabasz_score, davies_bouldin_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import (
    f1_score,
    accuracy_score,
    roc_auc_score,
    recall_score,
    precision_score,
    confusion_matrix,
    make_scorer,
    precision_recall_curve,
    roc_curve,
)

In [2]:
df = pd.read_csv("hiv_exp.csv")

In [3]:
df.head()

State  years  gender  Mstatus  fam  numb  Edulevel  empstatus  monthIncome  \
0    1.0    4.0     1.0      2.0  2.0   4.0       4.0        2.0          1.0   
1    1.0    3.0     2.0      4.0  2.0   4.0       3.0        3.0          1.0   
2    1.0    2.0     2.0      1.0  1.0   4.0       1.0        4.0          1.0   
3    1.0    3.0     2.0      2.0  1.0   4.0       4.0        1.0          4.0   
4    1.0    5.0     1.0      2.0  2.0   4.0       3.0        1.0          3.0   

   treatmentreg  ...  comfortability_copy3  comfortability_copy2  \
0           1.0  ...                   5.0                   5.0   
1           1.0  ...                   5.0                   5.0   
2           4.0  ...                   4.0                   4.0   
3           1.0  ...                   5.0                   5.0   
4           1.0  ...                   4.0                   4.0   

   comfortability_copy1  comfortability_copy  Over_Comf  Cat_Comfort  \
0                   5.0                  5.0       94.0          1.0   
1                   4.0                  5.0       89.0          1.0   
2                   4.0                  4.0       78.0          0.0   
3                   5.0                  5.0       95.0          1.0   
4                   4.0                  5.0       77.0          0.0   

   Cat_Perc  Cat_Perception  experience_score_raw  ExperienceScore  
0      94.0             1.0             25.127047                1  
1      89.0             1.0             23.936960                0  
2      78.0             0.0             20.549819                2  
3      95.0             1.0             25.513072                1  
4      77.0             0.0             21.151728                2  

[5 rows x 40 columns]

In [4]:
df1=df.copy()

In [5]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [6]:
df1.head()

State  years  gender  Mstatus  fam  numb  Edulevel  empstatus  monthIncome  \
0    1.0    4.0     1.0      2.0  2.0   4.0       4.0        2.0          1.0   
1    1.0    3.0     2.0      4.0  2.0   4.0       3.0        3.0          1.0   
2    1.0    2.0     2.0      1.0  1.0   4.0       1.0        4.0          1.0   
3    1.0    3.0     2.0      2.0  1.0   4.0       4.0        1.0          4.0   
4    1.0    5.0     1.0      2.0  2.0   4.0       3.0        1.0          3.0   

   treatmentreg  durationTLHIV  durRecCare  TimRecCare  Satisfaction  HIVdiag  \
0           1.0            5.0         5.0         5.0           1.0      1.0   
1           1.0            4.0         4.0         4.0           1.0      5.0   
2           4.0            3.0         3.0         3.0           1.0      5.0   
3           1.0            5.0         5.0         5.0           1.0      1.0   
4           1.0            5.0         5.0         5.0           2.0      4.0   

   comfortability  comfortability_copy17  comfortability_copy16  \
0             5.0                    5.0                    5.0   
1             5.0                    5.0                    4.0   
2             4.0                    4.0                    4.0   
3             5.0                    5.0                    5.0   
4             4.0                    4.0                    4.0   

   comfortability_copy15  comfortability_copy14  comfortability_copy13  \
0                    5.0                    4.0                    5.0   
1                    4.0                    5.0                    4.0   
2                    4.0                    5.0                    4.0   
3                    5.0                    5.0                    5.0   
4                    4.0                    4.0                    4.0   

   comfortability_copy12  comfortability_copy11  comfortability_copy10  \
0                    5.0                    5.0                    5.0   
1                    4.0                    5.0                    5.0   
2                    4.0                    4.0                    5.0   
3                    5.0                    5.0                    5.0   
4                    4.0                    4.0                    4.0   

   comfortability_copy9  comfortability_copy8  comfortability_copy7  \
0                   5.0                   5.0                   5.0   
1                   5.0                   5.0                   5.0   
2                   4.0                   4.0                   4.0   
3                   5.0                   5.0                   5.0   
4                   4.0                   4.0                   4.0   

   comfortability_copy6  comfortability_copy5  comfortability_copy4  \
0                   5.0                   5.0                   5.0   
1                   4.0                   5.0                   5.0   
2                   4.0                   4.0                   4.0   
3                   5.0                   5.0                   5.0   
4                   4.0                   4.0                   4.0   

   comfortability_copy3  comfortability_copy2  comfortability_copy1  \
0                   5.0                   5.0                   5.0   
1                   5.0                   5.0                   4.0   
2                   4.0                   4.0                   4.0   
3                   5.0                   5.0                   5.0   
4                   4.0                   4.0                   4.0   

   comfortability_copy  Over_Comf  Cat_Comfort  Cat_Perc  Cat_Perception  \
0                  5.0       94.0          1.0      94.0             1.0   
1                  5.0       89.0          1.0      89.0             1.0   
2                  4.0       78.0          0.0      78.0             0.0   
3                  5.0       95.0          1.0      95.0             1.0   
4                  5.0       77.0          0.0      77.0             0.0   

In [7]:
#renaming columns 

In [8]:
# Dictionary mapping old names to new ones
rename_dict = {
    'Mstatus': 'Marital_Status',
    'Cat_Perc': 'Perception_Category',
    'years': 'Years_on_Treatment',
    'Over_Comf': 'Overall_Comfort_Level',
    'Edulevel': 'Education_Level',
    'monthIncome': 'Monthly_Income',
    'numb': 'Household_Size',
    'treatmentreg': 'Treatment_Regimen',
    'TimRecCare': 'Care_Timeliness',
    'comfortability_copy7': 'Comfort_StaffInteraction'
}

# Apply the renaming
df1.rename(columns=rename_dict, inplace=True)

# Optional: check the changes
print(df1[list(rename_dict.values())].head())

   Marital_Status  Perception_Category  Years_on_Treatment  \
0             2.0                 94.0                 4.0   
1             4.0                 89.0                 3.0   
2             1.0                 78.0                 2.0   
3             2.0                 95.0                 3.0   
4             2.0                 77.0                 5.0   

   Overall_Comfort_Level  Education_Level  Monthly_Income  Household_Size  \
0                   94.0              4.0             1.0             4.0   
1                   89.0              3.0             1.0             4.0   
2                   78.0              1.0             1.0             4.0   
3                   95.0              4.0             4.0             4.0   
4                   77.0              3.0             3.0             4.0   

   Treatment_Regimen  Care_Timeliness  Comfort_StaffInteraction  
0                1.0              5.0                       5.0  
1                1.0            

In [10]:
df1.head()

State  Years_on_Treatment  gender  Marital_Status  fam  Household_Size  \
0    1.0                 4.0     1.0             2.0  2.0             4.0   
1    1.0                 3.0     2.0             4.0  2.0             4.0   
2    1.0                 2.0     2.0             1.0  1.0             4.0   
3    1.0                 3.0     2.0             2.0  1.0             4.0   
4    1.0                 5.0     1.0             2.0  2.0             4.0   

   Education_Level  empstatus  Monthly_Income  Treatment_Regimen  \
0              4.0        2.0             1.0                1.0   
1              3.0        3.0             1.0                1.0   
2              1.0        4.0             1.0                4.0   
3              4.0        1.0             4.0                1.0   
4              3.0        1.0             3.0                1.0   

   durationTLHIV  durRecCare  Care_Timeliness  Satisfaction  HIVdiag  \
0            5.0         5.0              5.0           1.0      1.0   
1            4.0         4.0              4.0           1.0      5.0   
2            3.0         3.0              3.0           1.0      5.0   
3            5.0         5.0              5.0           1.0      1.0   
4            5.0         5.0              5.0           2.0      4.0   

   comfortability  comfortability_copy17  comfortability_copy16  \
0             5.0                    5.0                    5.0   
1             5.0                    5.0                    4.0   
2             4.0                    4.0                    4.0   
3             5.0                    5.0                    5.0   
4             4.0                    4.0                    4.0   

   comfortability_copy15  comfortability_copy14  comfortability_copy13  \
0                    5.0                    4.0                    5.0   
1                    4.0                    5.0                    4.0   
2                    4.0                    5.0                    4.0   
3                    5.0                    5.0                    5.0   
4                    4.0                    4.0                    4.0   

   comfortability_copy12  comfortability_copy11  comfortability_copy10  \
0                    5.0                    5.0                    5.0   
1                    4.0                    5.0                    5.0   
2                    4.0                    4.0                    5.0   
3                    5.0                    5.0                    5.0   
4                    4.0                    4.0                    4.0   

   comfortability_copy9  comfortability_copy8  Comfort_StaffInteraction  \
0                   5.0                   5.0                       5.0   
1                   5.0                   5.0                       5.0   
2                   4.0                   4.0                       4.0   
3                   5.0                   5.0                       5.0   
4                   4.0                   4.0                       4.0   

   comfortability_copy6  comfortability_copy5  comfortability_copy4  \
0                   5.0                   5.0                   5.0   
1                   4.0                   5.0                   5.0   
2                   4.0                   4.0                   4.0   
3                   5.0                   5.0                   5.0   
4                   4.0                   4.0                   4.0   

   comfortability_copy3  comfortability_copy2  comfortability_copy1  \
0                   5.0                   5.0                   5.0   
1                   5.0                   5.0                   4.0   
2                   4.0                   4.0                   4.0   
3                   5.0                   5.0                   5.0   
4                   4.0                   4.0                   4.0   

   comfortability_copy  Overall_Comfort_Level  Cat_Comfort  \
0                  5.0                

In [12]:
df1 = df1.drop (['experience_score_raw'], axis = 1)

In [13]:
df1.head()

State  Years_on_Treatment  gender  Marital_Status  fam  Household_Size  \
0    1.0                 4.0     1.0             2.0  2.0             4.0   
1    1.0                 3.0     2.0             4.0  2.0             4.0   
2    1.0                 2.0     2.0             1.0  1.0             4.0   
3    1.0                 3.0     2.0             2.0  1.0             4.0   
4    1.0                 5.0     1.0             2.0  2.0             4.0   

   Education_Level  empstatus  Monthly_Income  Treatment_Regimen  \
0              4.0        2.0             1.0                1.0   
1              3.0        3.0             1.0                1.0   
2              1.0        4.0             1.0                4.0   
3              4.0        1.0             4.0                1.0   
4              3.0        1.0             3.0                1.0   

   durationTLHIV  durRecCare  Care_Timeliness  Satisfaction  HIVdiag  \
0            5.0         5.0              5.0           1.0      1.0   
1            4.0         4.0              4.0           1.0      5.0   
2            3.0         3.0              3.0           1.0      5.0   
3            5.0         5.0              5.0           1.0      1.0   
4            5.0         5.0              5.0           2.0      4.0   

   comfortability  comfortability_copy17  comfortability_copy16  \
0             5.0                    5.0                    5.0   
1             5.0                    5.0                    4.0   
2             4.0                    4.0                    4.0   
3             5.0                    5.0                    5.0   
4             4.0                    4.0                    4.0   

   comfortability_copy15  comfortability_copy14  comfortability_copy13  \
0                    5.0                    4.0                    5.0   
1                    4.0                    5.0                    4.0   
2                    4.0                    5.0                    4.0   
3                    5.0                    5.0                    5.0   
4                    4.0                    4.0                    4.0   

   comfortability_copy12  comfortability_copy11  comfortability_copy10  \
0                    5.0                    5.0                    5.0   
1                    4.0                    5.0                    5.0   
2                    4.0                    4.0                    5.0   
3                    5.0                    5.0                    5.0   
4                    4.0                    4.0                    4.0   

   comfortability_copy9  comfortability_copy8  Comfort_StaffInteraction  \
0                   5.0                   5.0                       5.0   
1                   5.0                   5.0                       5.0   
2                   4.0                   4.0                       4.0   
3                   5.0                   5.0                       5.0   
4                   4.0                   4.0                       4.0   

   comfortability_copy6  comfortability_copy5  comfortability_copy4  \
0                   5.0                   5.0                   5.0   
1                   4.0                   5.0                   5.0   
2                   4.0                   4.0                   4.0   
3                   5.0                   5.0                   5.0   
4                   4.0                   4.0                   4.0   

   comfortability_copy3  comfortability_copy2  comfortability_copy1  \
0                   5.0                   5.0                   5.0   
1                   5.0                   5.0                   4.0   
2                   4.0                   4.0                   4.0   
3                   5.0                   5.0                   5.0   
4                   4.0                   4.0                   4.0   

   comfortability_copy  Overall_Comfort_Level  Cat_Comfort  \
0                  5.0                

# model building

In [15]:
x = df1.drop(['ExperienceScore'], axis = 1)
y = df1['ExperienceScore']

In [16]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size= 0.3, random_state =1)

In [17]:
print("Shape of Training set : ", x_train.shape)
print("Shape of Training set : ", x_test.shape)
print(y_train.value_counts(normalize = True))
print("Percentage of classes in test set:")
print(y_test.value_counts(normalize = True))

Shape of Training set :  (343, 38)
Shape of Training set :  (148, 38)
ExperienceScore
2    0.352770
0    0.329446
1    0.317784
Name: proportion, dtype: float64
Percentage of classes in test set:
ExperienceScore
1    0.391892
0    0.331081
2    0.277027
Name: proportion, dtype: float64


In [19]:
#training the model with logistic regression
model = LogisticRegression()
model.fit(x_train, y_train)

LogisticRegression()

In [20]:
y_pred = model.predict(x_test)

In [21]:
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

In [22]:
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
#print("\nROC-AUC Score:", roc_auc_score(y_test, model.predict_proba(x_test[:, 1])))
accuracy = accuracy_score(y_test, y_pred)
print("Model Accuracy:", accuracy)

Confusion Matrix:
 [[24 10 15]
 [10 48  0]
 [ 9  0 32]]

Classification Report:
               precision    recall  f1-score   support

           0       0.56      0.49      0.52        49
           1       0.83      0.83      0.83        58
           2       0.68      0.78      0.73        41

    accuracy                           0.70       148
   macro avg       0.69      0.70      0.69       148
weighted avg       0.70      0.70      0.70       148

Model Accuracy: 0.7027027027027027


based on the confusion matrux, the true positives is 104, the true negative is 208, false positive is 44, false negative is 44

In [26]:
#building model with Random forest classifier
from sklearn.ensemble import RandomForestClassifier

In [27]:
rf = RandomForestClassifier (n_estimators=100, random_state=42)

In [28]:
rf.fit(x_train, y_train)

RandomForestClassifier(random_state=42)

In [29]:
y_pred_rf = rf.predict(x_test)

In [38]:
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_rf))
print("\nClassification Report:\n", classification_report(y_test, y_pred_rf))
#print("\nROC-AUC Score:", roc_auc_score(y_test, model.predict_proba(x_test[:, 1])))
accuracy = accuracy_score(y_test, y_pred_rf)
print("Model Accuracy:", accuracy)

Confusion Matrix:
 [[42  2  5]
 [ 2 56  0]
 [ 1  0 40]]

Classification Report:
               precision    recall  f1-score   support

           0       0.93      0.86      0.89        49
           1       0.97      0.97      0.97        58
           2       0.89      0.98      0.93        41

    accuracy                           0.93       148
   macro avg       0.93      0.93      0.93       148
weighted avg       0.93      0.93      0.93       148

Model Accuracy: 0.9324324324324325


In [30]:
#buidling model with decison tree

In [32]:
dt = DecisionTreeClassifier(random_state = 42)
dt.fit(x_train, y_train)
y_pred_dt = dt.predict(x_test)

In [39]:
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_dt))
print("\nClassification Report:\n", classification_report(y_test, y_pred_dt))
#print("\nROC-AUC Score:", roc_auc_score(y_test, model.predict_proba(x_test[:, 1])))
accuracy = accuracy_score(y_test, y_pred_dt)
print("Model Accuracy:", accuracy)

Confusion Matrix:
 [[41  3  5]
 [ 6 52  0]
 [ 2  0 39]]

Classification Report:
               precision    recall  f1-score   support

           0       0.84      0.84      0.84        49
           1       0.95      0.90      0.92        58
           2       0.89      0.95      0.92        41

    accuracy                           0.89       148
   macro avg       0.89      0.89      0.89       148
weighted avg       0.89      0.89      0.89       148

Model Accuracy: 0.8918918918918919


In [35]:
#building model with xgboost classifier
from sklearn import svm

In [36]:
svm_model = svm.SVC(random_state=42)
svm_model.fit(x_train, y_train)

SVC(random_state=42)

In [37]:
y_pred_svm = svm_model.predict(x_test)

In [40]:
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_svm))
print("\nClassification Report:\n", classification_report(y_test, y_pred_svm))
#print("\nROC-AUC Score:", roc_auc_score(y_test, model.predict_proba(x_test[:, 1])))
accuracy = accuracy_score(y_test, y_pred_svm)
print("Model Accuracy:", accuracy)

Confusion Matrix:
 [[30 10  9]
 [ 0 58  0]
 [ 0  0 41]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.61      0.76        49
           1       0.85      1.00      0.92        58
           2       0.82      1.00      0.90        41

    accuracy                           0.87       148
   macro avg       0.89      0.87      0.86       148
weighted avg       0.89      0.87      0.86       148

Model Accuracy: 0.8716216216216216


In [42]:
import ipywidgets as widgets
from IPython.display import display, clear_output
import pandas as pd

# Define the features you're using
features = [
    'Marital_Status',
    'Perception_Category',
    'Years_on_Treatment',
    'Overall_Comfort_Level',
    'Education_Level',
    'Monthly_Income',
    'Household_Size',
    'Treatment_Regimen',
    'Care_Timeliness',
    'Comfort_StaffInteraction'
]

# Create numeric input boxes for each feature
input_widgets = {}
for feature in features:
    input_widgets[feature] = widgets.FloatText(
        description=feature.replace("_", " ")[:18],  # Adjust label length for UI
        layout=widgets.Layout(width='400px')
    )

# Arrange the widgets in a vertical box
input_box = widgets.VBox([input_widgets[feature] for feature in features])

# Create the predict button and output area
predict_button = widgets.Button(description="Predict Experience Score", button_style='success')
output = widgets.Output()

# Define prediction function
def on_predict_clicked(b):
    with output:
        clear_output()
        # Gather inputs into DataFrame
        input_data = pd.DataFrame({feature: [input_widgets[feature].value] for feature in features})
        try:
            prediction = model.predict(input_data)[0]
            label_map = {1: "Positive Experience", 0: "Neutral Experience", 2: "Negative Experience"}
            print(f"Predicted Experience Score: {label_map.get(prediction, 'Unknown')} (Class: {prediction})")
        except Exception as e:
            print(f"Error during prediction: {e}")

# Link button click to function
predict_button.on_click(on_predict_clicked)

# Display all components
display(input_box, predict_button, output)

Button(button_style='success', description='Predict Experience Score', style=ButtonStyle())

Output()

In [46]:
features = [
    'Marital_Status',
    'Perception_Category',
    'Years_on_Treatment',
    'Overall_Comfort_Level',
    'Education_Level',
    'Monthly_Income',
    'Household_Size',
    'Treatment_Regimen',
    'Care_Timeliness',
    'Comfort_StaffInteraction'
]

target = 'ExperienceScore'

x = df1[features]
y = df1[target]

# 5. Train the Random Forest model
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42, stratify=y)
model = RandomForestClassifier(random_state=42)
model.fit(x_train, y_train)

RandomForestClassifier(random_state=42)

In [47]:
import ipywidgets as widgets
from IPython.display import display, clear_output
import pandas as pd

# Define the features you're using
features = [
    'Marital_Status',
    'Perception_Category',
    'Years_on_Treatment',
    'Overall_Comfort_Level',
    'Education_Level',
    'Monthly_Income',
    'Household_Size',
    'Treatment_Regimen',
    'Care_Timeliness',
    'Comfort_StaffInteraction'
]

# Create numeric input boxes for each feature
input_widgets = {}
for feature in features:
    input_widgets[feature] = widgets.FloatText(
        description=feature.replace("_", " ")[:18],  # Adjust label length for UI
        layout=widgets.Layout(width='400px')
    )

# Arrange the widgets in a vertical box
input_box = widgets.VBox([input_widgets[feature] for feature in features])

# Create the predict button and output area
predict_button = widgets.Button(description="Predict Experience Score", button_style='success')
output = widgets.Output()

# Define prediction function
def on_predict_clicked(b):
    with output:
        clear_output()
        # Gather inputs into DataFrame
        input_data = pd.DataFrame({feature: [input_widgets[feature].value] for feature in features})
        try:
            prediction = model.predict(input_data)[0]
            label_map = {1: "Positive Experience", 0: "Neutral Experience", 2: "Negative Experience"}
            print(f"Predicted Experience Score: {label_map.get(prediction, 'Unknown')} (Class: {prediction})")
        except Exception as e:
            print(f"Error during prediction: {e}")

# Link button click to function
predict_button.on_click(on_predict_clicked)

# Display all components
display(input_box, predict_button, output)

Button(button_style='success', description='Predict Experience Score', style=ButtonStyle())

Output()

In [50]:
#saving the model
import joblib

In [51]:
joblib.dump(model, 'hiv_score_model.pkl')

['hiv_score_model.pkl']

In [54]:
df1.head()

State  Years_on_Treatment  gender  Marital_Status  fam  Household_Size  \
0    1.0                 4.0     1.0             2.0  2.0             4.0   
1    1.0                 3.0     2.0             4.0  2.0             4.0   
2    1.0                 2.0     2.0             1.0  1.0             4.0   
3    1.0                 3.0     2.0             2.0  1.0             4.0   
4    1.0                 5.0     1.0             2.0  2.0             4.0   

   Education_Level  empstatus  Monthly_Income  Treatment_Regimen  \
0              4.0        2.0             1.0                1.0   
1              3.0        3.0             1.0                1.0   
2              1.0        4.0             1.0                4.0   
3              4.0        1.0             4.0                1.0   
4              3.0        1.0             3.0                1.0   

   durationTLHIV  durRecCare  Care_Timeliness  Satisfaction  HIVdiag  \
0            5.0         5.0              5.0           1.0      1.0   
1            4.0         4.0              4.0           1.0      5.0   
2            3.0         3.0              3.0           1.0      5.0   
3            5.0         5.0              5.0           1.0      1.0   
4            5.0         5.0              5.0           2.0      4.0   

   comfortability  comfortability_copy17  comfortability_copy16  \
0             5.0                    5.0                    5.0   
1             5.0                    5.0                    4.0   
2             4.0                    4.0                    4.0   
3             5.0                    5.0                    5.0   
4             4.0                    4.0                    4.0   

   comfortability_copy15  comfortability_copy14  comfortability_copy13  \
0                    5.0                    4.0                    5.0   
1                    4.0                    5.0                    4.0   
2                    4.0                    5.0                    4.0   
3                    5.0                    5.0                    5.0   
4                    4.0                    4.0                    4.0   

   comfortability_copy12  comfortability_copy11  comfortability_copy10  \
0                    5.0                    5.0                    5.0   
1                    4.0                    5.0                    5.0   
2                    4.0                    4.0                    5.0   
3                    5.0                    5.0                    5.0   
4                    4.0                    4.0                    4.0   

   comfortability_copy9  comfortability_copy8  Comfort_StaffInteraction  \
0                   5.0                   5.0                       5.0   
1                   5.0                   5.0                       5.0   
2                   4.0                   4.0                       4.0   
3                   5.0                   5.0                       5.0   
4                   4.0                   4.0                       4.0   

   comfortability_copy6  comfortability_copy5  comfortability_copy4  \
0                   5.0                   5.0                   5.0   
1                   4.0                   5.0                   5.0   
2                   4.0                   4.0                   4.0   
3                   5.0                   5.0                   5.0   
4                   4.0                   4.0                   4.0   

   comfortability_copy3  comfortability_copy2  comfortability_copy1  \
0                   5.0                   5.0                   5.0   
1                   5.0                   5.0                   4.0   
2                   4.0                   4.0                   4.0   
3                   5.0                   5.0                   5.0   
4                   4.0                   4.0                   4.0   

   comfortability_copy  Overall_Comfort_Level  Cat_Comfort  \
0                  5.0                

In [66]:
df1['Comfort_StaffInteraction'].describe().T

count    491.000000
mean       4.505092
std        0.614015
min        2.000000
25%        4.000000
50%        5.000000
75%        5.000000
max        5.000000
Name: Comfort_StaffInteraction, dtype: float64

In [55]:
df1['Perception_Category'].value_counts()

Perception_Category
95.0    122
76.0     30
77.0     25
80.0     21
94.0     18
81.0     18
87.0     17
91.0     16
79.0     16
89.0     15
78.0     15
86.0     15
82.0     14
84.0     14
75.0     14
73.0     14
92.0     13
93.0     12
90.0     12
85.0      9
74.0      8
88.0      8
83.0      6
66.0      6
72.0      5
67.0      4
71.0      3
65.0      3
64.0      3
69.0      3
68.0      3
61.0      2
70.0      2
59.0      2
57.0      1
63.0      1
44.0      1
Name: count, dtype: int64

In [57]:
df1['Overall_Comfort_Level'].describe().T

count    491.000000
mean      84.506173
std        9.188889
min       44.000000
25%       77.000000
50%       85.000000
75%       94.000000
max       95.000000
Name: Overall_Comfort_Level, dtype: float64

In [69]:
import sklearn

In [70]:
print(sklearn.__version__)

1.6.1


In [71]:
!python --version

Python 3.9.7


In [72]:
#resaving the model using joblib

In [73]:
import joblib

In [74]:
joblib.dump(model, 'hiv_model_joblib.pkl')

['hiv_model_joblib.pkl']

In [76]:
x.head()

Marital_Status  Perception_Category  Years_on_Treatment  \
0             2.0                 94.0                 4.0   
1             4.0                 89.0                 3.0   
2             1.0                 78.0                 2.0   
3             2.0                 95.0                 3.0   
4             2.0                 77.0                 5.0   

   Overall_Comfort_Level  Education_Level  Monthly_Income  Household_Size  \
0                   94.0              4.0             1.0             4.0   
1                   89.0              3.0             1.0             4.0   
2                   78.0              1.0             1.0             4.0   
3                   95.0              4.0             4.0             4.0   
4                   77.0              3.0             3.0             4.0   

   Treatment_Regimen  Care_Timeliness  Comfort_StaffInteraction  
0                1.0              5.0                       5.0  
1                1.0              4.0                       5.0  
2                4.0              3.0                       4.0  
3                1.0              5.0                       5.0  
4                1.0              5.0                       4.0

In [77]:
df1.head(2)

State  Years_on_Treatment  gender  Marital_Status  fam  Household_Size  \
0    1.0                 4.0     1.0             2.0  2.0             4.0   
1    1.0                 3.0     2.0             4.0  2.0             4.0   

   Education_Level  empstatus  Monthly_Income  Treatment_Regimen  \
0              4.0        2.0             1.0                1.0   
1              3.0        3.0             1.0                1.0   

   durationTLHIV  durRecCare  Care_Timeliness  Satisfaction  HIVdiag  \
0            5.0         5.0              5.0           1.0      1.0   
1            4.0         4.0              4.0           1.0      5.0   

   comfortability  comfortability_copy17  comfortability_copy16  \
0             5.0                    5.0                    5.0   
1             5.0                    5.0                    4.0   

   comfortability_copy15  comfortability_copy14  comfortability_copy13  \
0                    5.0                    4.0                    5.0   
1                    4.0                    5.0                    4.0   

   comfortability_copy12  comfortability_copy11  comfortability_copy10  \
0                    5.0                    5.0                    5.0   
1                    4.0                    5.0                    5.0   

   comfortability_copy9  comfortability_copy8  Comfort_StaffInteraction  \
0                   5.0                   5.0                       5.0   
1                   5.0                   5.0                       5.0   

   comfortability_copy6  comfortability_copy5  comfortability_copy4  \
0                   5.0                   5.0                   5.0   
1                   4.0                   5.0                   5.0   

   comfortability_copy3  comfortability_copy2  comfortability_copy1  \
0                   5.0                   5.0                   5.0   
1                   5.0                   5.0                   4.0   

   comfortability_copy  Overall_Comfort_Level  Cat_Comfort  \
0                  5.0                   94.0          1.0   
1                  5.0                   89.0          1.0   

   Perception_Category  Cat_Perception  ExperienceScore  
0                 94.0             1.0                1  
1                 89.0             1.0                0

In [ ]:
4.0, 89.0, 3.0, 89.0, 3.0, 1.0, 4.0, 1.0, 4.0, 5.0

In [78]:
df1.head()

State  Years_on_Treatment  gender  Marital_Status  fam  Household_Size  \
0    1.0                 4.0     1.0             2.0  2.0             4.0   
1    1.0                 3.0     2.0             4.0  2.0             4.0   
2    1.0                 2.0     2.0             1.0  1.0             4.0   
3    1.0                 3.0     2.0             2.0  1.0             4.0   
4    1.0                 5.0     1.0             2.0  2.0             4.0   

   Education_Level  empstatus  Monthly_Income  Treatment_Regimen  \
0              4.0        2.0             1.0                1.0   
1              3.0        3.0             1.0                1.0   
2              1.0        4.0             1.0                4.0   
3              4.0        1.0             4.0                1.0   
4              3.0        1.0             3.0                1.0   

   durationTLHIV  durRecCare  Care_Timeliness  Satisfaction  HIVdiag  \
0            5.0         5.0              5.0           1.0      1.0   
1            4.0         4.0              4.0           1.0      5.0   
2            3.0         3.0              3.0           1.0      5.0   
3            5.0         5.0              5.0           1.0      1.0   
4            5.0         5.0              5.0           2.0      4.0   

   comfortability  comfortability_copy17  comfortability_copy16  \
0             5.0                    5.0                    5.0   
1             5.0                    5.0                    4.0   
2             4.0                    4.0                    4.0   
3             5.0                    5.0                    5.0   
4             4.0                    4.0                    4.0   

   comfortability_copy15  comfortability_copy14  comfortability_copy13  \
0                    5.0                    4.0                    5.0   
1                    4.0                    5.0                    4.0   
2                    4.0                    5.0                    4.0   
3                    5.0                    5.0                    5.0   
4                    4.0                    4.0                    4.0   

   comfortability_copy12  comfortability_copy11  comfortability_copy10  \
0                    5.0                    5.0                    5.0   
1                    4.0                    5.0                    5.0   
2                    4.0                    4.0                    5.0   
3                    5.0                    5.0                    5.0   
4                    4.0                    4.0                    4.0   

   comfortability_copy9  comfortability_copy8  Comfort_StaffInteraction  \
0                   5.0                   5.0                       5.0   
1                   5.0                   5.0                       5.0   
2                   4.0                   4.0                       4.0   
3                   5.0                   5.0                       5.0   
4                   4.0                   4.0                       4.0   

   comfortability_copy6  comfortability_copy5  comfortability_copy4  \
0                   5.0                   5.0                   5.0   
1                   4.0                   5.0                   5.0   
2                   4.0                   4.0                   4.0   
3                   5.0                   5.0                   5.0   
4                   4.0                   4.0                   4.0   

   comfortability_copy3  comfortability_copy2  comfortability_copy1  \
0                   5.0                   5.0                   5.0   
1                   5.0                   5.0                   4.0   
2                   4.0                   4.0                   4.0   
3                   5.0                   5.0                   5.0   
4                   4.0                   4.0                   4.0   

   comfortability_copy  Overall_Comfort_Level  Cat_Comfort  \
0                  5.0                

In [80]:
df.head(2)

State  years  gender  Mstatus  fam  numb  Edulevel  empstatus  monthIncome  \
0    1.0    4.0     1.0      2.0  2.0   4.0       4.0        2.0          1.0   
1    1.0    3.0     2.0      4.0  2.0   4.0       3.0        3.0          1.0   

   treatmentreg  durationTLHIV  durRecCare  TimRecCare  Satisfaction  HIVdiag  \
0           1.0            5.0         5.0         5.0           1.0      1.0   
1           1.0            4.0         4.0         4.0           1.0      5.0   

   comfortability  comfortability_copy17  comfortability_copy16  \
0             5.0                    5.0                    5.0   
1             5.0                    5.0                    4.0   

   comfortability_copy15  comfortability_copy14  comfortability_copy13  \
0                    5.0                    4.0                    5.0   
1                    4.0                    5.0                    4.0   

   comfortability_copy12  comfortability_copy11  comfortability_copy10  \
0                    5.0                    5.0                    5.0   
1                    4.0                    5.0                    5.0   

   comfortability_copy9  comfortability_copy8  comfortability_copy7  \
0                   5.0                   5.0                   5.0   
1                   5.0                   5.0                   5.0   

   comfortability_copy6  comfortability_copy5  comfortability_copy4  \
0                   5.0                   5.0                   5.0   
1                   4.0                   5.0                   5.0   

   comfortability_copy3  comfortability_copy2  comfortability_copy1  \
0                   5.0                   5.0                   5.0   
1                   5.0                   5.0                   4.0   

   comfortability_copy  Over_Comf  Cat_Comfort  Cat_Perc  Cat_Perception  \
0                  5.0       94.0          1.0      94.0             1.0   
1                  5.0       89.0          1.0      89.0             1.0   

   experience_score_raw  ExperienceScore  
0             25.127047                1  
1             23.936960                0

In [81]:
df['years'].value_counts()

years
3.0    180
4.0    121
2.0     98
5.0     61
1.0     31
Name: count, dtype: int64